# Project Name
TARGET = PluckEcho

# Sources
CPP_SOURCES = PluckEcho.cpp \
ev_theory/theory.cpp \
ev_theory/rhythm.cpp

# Library Locations
LIBDAISY_DIR = ../../libDaisy
DAISYSP_DIR = ../../DaisySP

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

